version: 2
updates:
  - package-ecosystem: pip
    directory: /package-project/src
    schedule:
      interval: monthly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
